server:
  port: 9406
spring:
  application:
    name: user-service
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/general
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.zacharyz.userentity.entity
  global-config:
    id-type: 2
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true